In [1]:
import numpy as np
import pandas as pd

# Numpy 教學
## 1. Numpy array 建立

In [3]:
Zeros = np.zeros((3, 3))
Ones = np.ones((3, 3))
Empty = np.empty((3, 3))
Arange = np.arange(0, 12, 3)
Line = np.linspace(0, 12, 3)
Reshape = Zeros.reshape(-1)
print(Zeros, Ones, Empty, Arange, Line, Reshape, sep = '\n\n')

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 9.13033314e-321]
 [1.29653943e-311 1.29653943e-311 1.29748050e-311]]

[0 3 6 9]

[ 0.  6. 12.]

[0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [11]:
Zeros.reshape(-1)


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## 2. Numpy 計算

In [12]:
arr = np.arange(0, 12).reshape((3, 4))
sum1 = np.sum(arr, axis = 0)
sum2 = np.sum(arr, axis = 1)
sum3 = np.sum(arr, axis = (0, 1))
sum4 = np.sum(arr, axis = (1, 0))
sum5 = np.sum(arr)
print(arr, '\n')
print(f'sum1, sum2, sum3, sum4, sum5 = ({sum1}, {sum2}, {sum3}, {sum4}, {sum5})')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

sum1, sum2, sum3, sum4, sum5 = ([12 15 18 21], [ 6 22 38], 66, 66, 66)


In [35]:
print(sum1 + sum1, sum1 - sum1, sum1 * 3, sum1 / 2, sep = '\n\n')
# sum1 + sum2

[24 30 36 42]

[0 0 0 0]

[36 45 54 63]

[ 6.   7.5  9.  10.5]


In [36]:
print(arr == 5, arr > 5, arr <5, sep = '\n\n')

[[False False False False]
 [False  True False False]
 [False False False False]]

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]

[[ True  True  True  True]
 [ True False False False]
 [False False False False]]


## 3. Numpy IO

In [37]:
np.save('arr.npy', arr)
arr = np.load('arr.npy')

# Pandas 教學
## 1. Pandas 型別
* Series
* Dataframe

In [13]:
# ------------- Series -------------

# From numpy array
series1 = pd.Series(sum1)

# From Python's list
series2 = pd.Series([1, 2, 3, 4])

print(series1, series2, sep = '\n\n')

0    12
1    15
2    18
3    21
dtype: int32

0    1
1    2
2    3
3    4
dtype: int64


In [21]:
# ------------- Dataframe -------------
dates = pd.date_range('20210101',periods = 6)
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns = [f"col{i}" for i in range(4)])
print(df, '\n')
print(df.index, df.columns, df.describe(), sep = '\n\n')

                col0      col1      col2      col3
2021-01-01  1.073273  1.141357 -0.034180  1.960954
2021-01-02  0.835013  2.486413 -0.278681 -1.777539
2021-01-03  0.271098 -0.493818 -1.048081  0.148416
2021-01-04 -1.018793  0.349442 -1.698479 -1.204727
2021-01-05  0.966700  1.064096  1.023433  0.588772
2021-01-06  0.505929 -0.422949 -1.459850  1.684126 

DatetimeIndex(['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04',
               '2021-01-05', '2021-01-06'],
              dtype='datetime64[ns]', freq='D')

Index(['col0', 'col1', 'col2', 'col3'], dtype='object')

           col0      col1      col2      col3
count  6.000000  6.000000  6.000000  6.000000
mean   0.438870  0.687423 -0.582640  0.233334
std    0.774006  1.124881  1.020186  1.505632
min   -1.018793 -0.493818 -1.698479 -1.777539
25%    0.329806 -0.229851 -1.356908 -0.866441
50%    0.670471  0.706769 -0.663381  0.368594
75%    0.933779  1.122041 -0.095305  1.410287
max    1.073273  2.486413  1.023433  1.960954


## 2. IO

In [29]:
df = pd.read_csv('homework.csv')
# df.to_csv(index = False)

## 3. index
* simple
* loc
* iloc
* ix(deprecated in 0.20.0 version)

In [22]:
# simple
print(df['col1'], df[['col1', 'col2']], df[:'2021-01-02']['col1'], sep = '\n\n')
print()

# loc (先 row 後 column)
print(df.loc[:'2021-01-02']['col1'], sep = '\n\n')
print()
# df['col1']

# iloc (先 row 後 column)
print(df.iloc[:2][:3], sep = '\n\n')
print()

# ix (先 row 後 column)
# print(df.ix[:2][:col3], sep = '\n\n')
# print()


2021-01-01    1.141357
2021-01-02    2.486413
2021-01-03   -0.493818
2021-01-04    0.349442
2021-01-05    1.064096
2021-01-06   -0.422949
Freq: D, Name: col1, dtype: float64

                col1      col2
2021-01-01  1.141357 -0.034180
2021-01-02  2.486413 -0.278681
2021-01-03 -0.493818 -1.048081
2021-01-04  0.349442 -1.698479
2021-01-05  1.064096  1.023433
2021-01-06 -0.422949 -1.459850

2021-01-01    1.141357
2021-01-02    2.486413
Freq: D, Name: col1, dtype: float64

2021-01-01    1.141357
2021-01-02    2.486413
Freq: D, Name: col1, dtype: float64

                col0      col1      col2      col3
2021-01-01  1.073273  1.141357 -0.034180  1.960954
2021-01-02  0.835013  2.486413 -0.278681 -1.777539



In [25]:
df

col0      col1      col2      col3      col4      col5      col6  \
0     -0.037418 -0.423133 -1.066878  0.463263 -0.130916 -1.153970 -0.598449   
1      0.818413 -1.120974 -0.581785 -1.280338 -0.713844  1.698914 -0.832480   
2     -2.090596 -0.868769 -1.778862  0.666989 -1.357663  0.433514 -1.617890   
3     -0.289783  1.151368  1.105835 -0.309009  0.186021  0.625453 -1.357677   
4      0.393337 -1.279473 -0.380730 -3.059202 -1.027667  0.121893  0.088561   
...         ...       ...       ...       ...       ...       ...       ...   
99995  1.169373 -1.659422  1.407234  0.625086 -1.779651  0.684514 -0.564882   
99996  0.151488 -0.419368  0.077559 -0.997915 -1.871504 -2.338928 -1.914960   
99997  1.208199 -1.139107  0.074972  0.371717  0.176787 -0.523450  1.561540   
99998  0.038288  0.784779 -0.557020  2.462814  1.129594 -1.292801 -0.650390   
99999 -0.017763  0.077523 -2.197524 -0.572833  0.476823  0.217154  0.006123   

           col7      col8      col9  ...     col70     col71     col72  \
0     -0.327957 -0.007907 -0.464428  ...  0.222763 -1.229966 -0.667184   
1     -0.313192 -1.036266 -1.098621  ... -0.445329 -0.693601  0.795167   
2     -1.220858 -0.566980 -1.237635  ...  1.152130 -0.058108 -0.105104   
3      0.308579 -0.380738  1.335565  ... -0.683605  0.905133  1.328116   
4     -0.444649  0.643246 -0.258456  ... -0.030803 -1.994453 -0.304141   
...         ...       ...       ...  ...       ...       ...       ...   
99995 -0.159244  0.861659  0.476870  ... -0.226039  1.396990  0.559320   
99996 -2.855910  0.738012 -0.174478  ... -1.465184  0.402564  0.220336   
99997  1.371943 -1.379962 -1.025441  ...  1.928941 -0.331970  0.573593   
99998  0.715064 -1.328429  0.120543  ... -0.723951  0.122555 -1.811966   
99999  1.996641 -0.389060  0.095060  ...  0.680210 -0.572903 -1.494582   

          col73     col74     col75     col76     col77     col78     col79  
0     -0.102731 -1.310584 -0.702787  2.059981  0.608418 -0.020808  1.783352  
1     -1.051140  1.285994  0.653626  1.396237  0.080399  1.377073 -0.794819  
2      1.080918  0.924454 -0.019370 -0.948623 -0.981408 -0.251559  0.345169  
3      0.529399 -0.443334  1.276279  2.503925  0.613427  0.358716 -0.958212  
4     -1.626619 -0.737330  0.276077 -0.052384  0.645169 -0.728073 -0.051508  
...         ...       ...       ...       ...       ...       ...       ...  
99995  1.195908  0.486600 -1.544905 -1.052251  1.152265 -0.603716  1.214425  
99996 -0.065954  1.597364  0.512378 -0.935301  0.152723 -0.134673 -0.591142  
99997  0.163113  1.672773 -2.370009  0.746834  1.793470  1.268034 -0.520627  
99998 -0.859171  0.828031  0.699950 -1.044509 -1.729967  1.211119 -0.157613  
99999  1.278799 -0.569146 -0.013218  1.113988  0.275856 -1.133910  0.013100  

[100000 rows x 80 columns]

## 4. concat


In [26]:
# ------------- Dataframe -------------
dates = pd.date_range('20210101',periods = 6)
tmp = pd.DataFrame(np.random.randn(6, 2), index=dates, columns = [f"col{i}" for i in range(4, 6)])
print(tmp, '\n')

df1 = pd.concat([df, tmp], axis = 1)
df2 = pd.concat([df, tmp], axis = 0)
print(df1, df2, sep = '\n\n')

                col4      col5
2021-01-01  0.346403  1.207697
2021-01-02  0.525383 -0.807360
2021-01-03  0.833224  0.080126
2021-01-04  0.980468  0.998363
2021-01-05  0.478857 -0.969153
2021-01-06  0.113379 -0.438760 

                         col0      col1      col2      col3      col4  \
0                   -0.037418 -0.423133 -1.066878  0.463263 -0.130916   
1                    0.818413 -1.120974 -0.581785 -1.280338 -0.713844   
2                   -2.090596 -0.868769 -1.778862  0.666989 -1.357663   
3                   -0.289783  1.151368  1.105835 -0.309009  0.186021   
4                    0.393337 -1.279473 -0.380730 -3.059202 -1.027667   
...                       ...       ...       ...       ...       ...   
2021-01-02 00:00:00       NaN       NaN       NaN       NaN       NaN   
2021-01-03 00:00:00       NaN       NaN       NaN       NaN       NaN   
2021-01-04 00:00:00       NaN       NaN       NaN       NaN       NaN   
2021-01-05 00:00:00       NaN       NaN       NaN  

## 5. nan

In [28]:
df = pd.read_csv('homework.csv')
# drop 
df1 = df.dropna(axis = 0, how = 'any')

# 補零
df2 = df.fillna(value = 0)

# 用一個 dictionary 填補
df3 = df.fillna(value = {f"col{i}" : i for i in range(df.shape[1])})

# 判斷 df 裡是否有 nan
True in np.asarray(df.isnull())

False

In [31]:
np.asarray(df.isnull())

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [32]:
df

col0      col1      col2      col3      col4      col5      col6  \
0     -0.037418 -0.423133 -1.066878  0.463263 -0.130916 -1.153970 -0.598449   
1      0.818413 -1.120974 -0.581785 -1.280338 -0.713844  1.698914 -0.832480   
2     -2.090596 -0.868769 -1.778862  0.666989 -1.357663  0.433514 -1.617890   
3     -0.289783  1.151368  1.105835 -0.309009  0.186021  0.625453 -1.357677   
4      0.393337 -1.279473 -0.380730 -3.059202 -1.027667  0.121893  0.088561   
...         ...       ...       ...       ...       ...       ...       ...   
99995  1.169373 -1.659422  1.407234  0.625086 -1.779651  0.684514 -0.564882   
99996  0.151488 -0.419368  0.077559 -0.997915 -1.871504 -2.338928 -1.914960   
99997  1.208199 -1.139107  0.074972  0.371717  0.176787 -0.523450  1.561540   
99998  0.038288  0.784779 -0.557020  2.462814  1.129594 -1.292801 -0.650390   
99999 -0.017763  0.077523 -2.197524 -0.572833  0.476823  0.217154  0.006123   

           col7      col8      col9  ...     col70     col71     col72  \
0     -0.327957 -0.007907 -0.464428  ...  0.222763 -1.229966 -0.667184   
1     -0.313192 -1.036266 -1.098621  ... -0.445329 -0.693601  0.795167   
2     -1.220858 -0.566980 -1.237635  ...  1.152130 -0.058108 -0.105104   
3      0.308579 -0.380738  1.335565  ... -0.683605  0.905133  1.328116   
4     -0.444649  0.643246 -0.258456  ... -0.030803 -1.994453 -0.304141   
...         ...       ...       ...  ...       ...       ...       ...   
99995 -0.159244  0.861659  0.476870  ... -0.226039  1.396990  0.559320   
99996 -2.855910  0.738012 -0.174478  ... -1.465184  0.402564  0.220336   
99997  1.371943 -1.379962 -1.025441  ...  1.928941 -0.331970  0.573593   
99998  0.715064 -1.328429  0.120543  ... -0.723951  0.122555 -1.811966   
99999  1.996641 -0.389060  0.095060  ...  0.680210 -0.572903 -1.494582   

          col73     col74     col75     col76     col77     col78     col79  
0     -0.102731 -1.310584 -0.702787  2.059981  0.608418 -0.020808  1.783352  
1     -1.051140  1.285994  0.653626  1.396237  0.080399  1.377073 -0.794819  
2      1.080918  0.924454 -0.019370 -0.948623 -0.981408 -0.251559  0.345169  
3      0.529399 -0.443334  1.276279  2.503925  0.613427  0.358716 -0.958212  
4     -1.626619 -0.737330  0.276077 -0.052384  0.645169 -0.728073 -0.051508  
...         ...       ...       ...       ...       ...       ...       ...  
99995  1.195908  0.486600 -1.544905 -1.052251  1.152265 -0.603716  1.214425  
99996 -0.065954  1.597364  0.512378 -0.935301  0.152723 -0.134673 -0.591142  
99997  0.163113  1.672773 -2.370009  0.746834  1.793470  1.268034 -0.520627  
99998 -0.859171  0.828031  0.699950 -1.044509 -1.729967  1.211119 -0.157613  
99999  1.278799 -0.569146 -0.013218  1.113988  0.275856 -1.133910  0.013100  

[100000 rows x 80 columns]

In [33]:
print(df['col0'], df['col1'], df['col2'], df['col3'], sep = '\n\n')

0       -0.037418
1        0.818413
2       -2.090596
3       -0.289783
4        0.393337
           ...   
99995    1.169373
99996    0.151488
99997    1.208199
99998    0.038288
99999   -0.017763
Name: col0, Length: 100000, dtype: float64

0       -0.423133
1       -1.120974
2       -0.868769
3        1.151368
4       -1.279473
           ...   
99995   -1.659422
99996   -0.419368
99997   -1.139107
99998    0.784779
99999    0.077523
Name: col1, Length: 100000, dtype: float64

0       -1.066878
1       -0.581785
2       -1.778862
3        1.105835
4       -0.380730
           ...   
99995    1.407234
99996    0.077559
99997    0.074972
99998   -0.557020
99999   -2.197524
Name: col2, Length: 100000, dtype: float64

0        0.463263
1       -1.280338
2        0.666989
3       -0.309009
4       -3.059202
           ...   
99995    0.625086
99996   -0.997915
99997    0.371717
99998    2.462814
99999   -0.572833
Name: col3, Length: 100000, dtype: float64
